= README

This directory contains preliminary work for seting up an integration
testing environment using docker containers.

This is work in progress and not yet complete nor ready for testing.




== Docker installation

* ubuntu 14.04 LTS:
+
[source,sh]
----
  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
  sudo sh -c "echo deb https://get.docker.com/ubuntu docker main\
> /etc/apt/sources.list.d/docker.list"
  sudo apt-get update
  sudo apt-get install lxc-docker
----
+
Now let's get the latest centos docker image:
+
[source,sh]
----
sudo docker pull centos:latest
----

== Build and run shoal-related containers

=== shoal-server

To build a new docker image with shoal server and rabbitmq server:

[source,sh]
----
cd shoal-server
make build-image
----

Now you can launch a shoal server container with the following command:

[source,sh]
----
make run
----

To connect to the running shoal server container:

[source,sh]
----
make connect
----

To stop a running shoal-server container:

[source,sh]
----
make stop
----


=== squid-server

To build a new docker image with squid server with shoal agent reporting to shoal-server above:

[source,sh]
----
cd squid-server
make build-image
----


Now you can launch a squid server container with the following command:

[source,sh]
----
make run
----


To connect to the running squid server container:

[source,sh]
----
make connect
----

To stop a running squid-server container:

[source,sh]
----
make stop
----
